name: "github action with docker"

on:
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main


jobs:
  dhruva:
    runs-on: ubuntu-latest

    steps:
      - name: "check out the ci pipeline"
        uses: actions/checkout@v4

      - name: "login the docker"
        uses: docker/login-actions@v3
        with: 
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: "create the image"
        run: "docker build -t dhruvamaheshwari47/github_actions_docker_etp:latest ."

      - name: "push image on docker hub"
        run: "docker push dhruvamaheshwari47/github_actions_docker_etp:latest"